# Generated by Django 6.0.4 on 2026-07-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='contact.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ManyToManyField(related_name='chatted_with', to='contact.profile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.profile'),
        ),
    ]
